### ISSUE TITLE
an Android system-level crash: finalize() timed out

### ISSUE THREAD

**Issue by lby1992** [opentok/opentok-android-sdk-samples#147]
Hi, I get the crash below on **Fabric**:
```
Fatal Exception: java.util.concurrent.TimeoutException: com.opentok.android.Publisher.finalize() timed out after 10 seconds
       at com.opentok.android.PublisherKit.finalizeNative(PublisherKit.java)
       at com.opentok.android.PublisherKit.finalize(PublisherKit.java:512)
       at com.opentok.android.Publisher.finalize(Publisher.java:460)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
       at java.lang.Thread.run(Thread.java:761)
```
The version that I'm using is `opentok-android-sdk:2.11.0`, can anyone tell me why it occurred and how to fix it.
Thanks!

**Comment by marinaserranomontes** [comment]
Hi @lby1992,

Sorry about the delay in answering you. We are going to review it.

Best,
Marina

**Comment by lby1992** [comment]
@marinaserranomontes Ok.

**Comment by ArdyTokbox** [comment]
Hi @lby1992, I'm having some difficulty reproducing the reported issue. Were you able to reproduce it using one of the samples? Is there any more information you can you provide, possibly from Fabric  which could help us reproduce this issue?

**Comment by lby1992** [comment]
Hi, @ArdyTokbox , thanks for your reply. I also cloud not reproduce it, it only occurred in few times, I will try more ways to reproduce it and get more information about it, please don't close this issue for now.

**Comment by ArdyTokbox** [comment]
@lby1992 Ok, we'll leave the ticket open until further notice. Please let us know if you happen to come across more information

**Comment by marinaserranomontes** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed.

Please reopen if you still encounter this issue You can also contribute directly to samples by providing a patch.

Thank you!

**Comment by sumitnaharia** [comment]
Session 0: Exception while stopping repeating: 
                                                                                            android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): cancelRequest:272: Camera device no longer alive
                                                                                                at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:633)
                                                                                                at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
                                                                                                at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:926)
                                                                                                at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:378)
                                                                                                at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:514)
                                                                                                at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:228)
                                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                             Caused by: android.os.ServiceSpecificException: cancelRequest:272: Camera device no longer alive
                                                                                                at android.os.Parcel.readException(Parcel.java:1697)
                                                                                                at android.os.Parcel.readException(Parcel.java:1636)
                                                                                                at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:350)
                                                                                                at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:93)
                                                                                                at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:926) 
                                                                                                at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:378) 
                                                                                                at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:514) 
                                                                                                at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:228) 
                                                                                                at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                                at android.os.HandlerThread.run(HandlerThread.java:61) 
12-08 15:19:36.070 17309-17319/com.example.android.rippleeffectdemo E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
                                                                                      Process: com.example.android.rippleeffectdemo, PID: 17309
                                                                                      java.util.concurrent.TimeoutException: com.opentok.android.Publisher.finalize() timed out after 10 seconds
                                                                                          at com.opentok.android.PublisherKit.finalizeNative(Native Method)
                                                                                          at com.opentok.android.PublisherKit.finalize(PublisherKit.java:512)

**Comment by lby1992** [comment]
@marinaserranomontes @ArdyTokbox 
Hi, unfortunally this error occured agian. There is a user publishing her live stream, suddenly another app popup a dialog and my app crashed with this error.

**Comment by sumitnaharia** [comment]
Change the opentok version  you will not get this error  again

**Comment by lby1992** [comment]
Thanks for you reply, @sumitnaharia 
I have upgrade the sdk and see if it would occur again.

**Comment by tapz** [comment]
com.opentok.android:opentok-android-sdk:2.15.3

03-29 12:30:20.805  2657  2669 E AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
03-29 12:30:20.805  2657  2669 E AndroidRuntime: Process: myapp, PID: 2657
03-29 12:30:20.805  2657  2669 E AndroidRuntime: java.util.concurrent.TimeoutException: com.opentok.android.v3.Publisher.finalize() timed out after 60 seconds
03-29 12:30:20.805  2657  2669 E AndroidRuntime: 	at com.opentok.android.v3.Publisher.finalizeNative(Native Method)
03-29 12:30:20.805  2657  2669 E AndroidRuntime: 	at com.opentok.android.v3.Publisher.finalize(Publisher.java:523)
03-29 12:30:20.805  2657  2669 E AndroidRuntime: 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
03-29 12:30:20.805  2657  2669 E AndroidRuntime: 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
03-29 12:30:20.805  2657  2669 E AndroidRuntime: 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
03-29 12:30:20.805  2657  2669 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

**Comment by dean95** [comment]
Also getting this error:

```
E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
    Process: air.com.rosettastone.mobile.CoursePlayer.snapshot, PID: 1340
    java.util.concurrent.TimeoutException: com.opentok.android.v3.Publisher.finalize() timed out after 60 seconds
        at com.opentok.android.v3.Publisher.finalizeNative(Native Method)
        at com.opentok.android.v3.Publisher.finalize(Publisher.java:523)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:764)
```

Using 2.15.3 version. Please reopen the ticket.

**Comment by tapz** [comment]
I'm seeing this all the time. Could you please paste the code here, so I could see what is in Publisher.java:523? That would help to know if I'm doing something that breaks the Publisher object.
