### ISSUE TITLE
Can't find implementation of a native method

### ISSUE THREAD

**Issue by akinadude** [opentok/opentok-android-sdk-samples#219]
I forked this project https://github.com/njovy/AppRTCDemo and I've managed to make this example of working with webrtc work in loopback mode. As far as I understood, author of the original project had built webrtc library from sources using insructions from official site https://webrtc.org/native-code/android/.
Now in another project https://github.com/akinadude/Opentoktest a have added opentok gradle dependency.
I'm trying to make work the loopback mode using the same approach as in the forked project that I mentioned before. As I understood webrtc is already contained in opentok library. As a result I've faced with this runtime problem:

```
2019-05-16 17:12:11.112 16856-16902/ru.akinadude.opentoktest E/art: No implementation found for void org.webrtc.PeerConnectionFactory.initializeInternalTracer() (tried Java_org_webrtc_PeerConnectionFactory_initializeInternalTracer and Java_org_webrtc_PeerConnectionFactory_initializeInternalTracer__)
    
    --------- beginning of crash
2019-05-16 17:12:11.113 16856-16902/ru.akinadude.opentoktest E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: ru.akinadude.opentoktest, PID: 16856
    java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.initializeInternalTracer() (tried Java_org_webrtc_PeerConnectionFactory_initializeInternalTracer and Java_org_webrtc_PeerConnectionFactory_initializeInternalTracer__)
        at org.webrtc.PeerConnectionFactory.initializeInternalTracer(Native Method)
        at ru.akinadude.opentoktest.video.PeerConnectionClient.createPeerConnectionFactoryInternal(PeerConnectionClient.java:353)
        at ru.akinadude.opentoktest.video.PeerConnectionClient.access$300(PeerConnectionClient.java:44)
        at ru.akinadude.opentoktest.video.PeerConnectionClient$1.run(PeerConnectionClient.java:302)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
```

It seems like Java native method can't find its implementation in the native library.
I have found in the final apk native libraries opentok.so. Does it contain native methods from original webrtc?
Can I somehow link calls from Java/Kotlin to native library opentok.so to make my sample work?

**Comment by robjperez** [comment]
HI @akinadude, unfortunately webrtc functions are not exported in our binary library so you cannot call them through libopentok.so.
