### ISSUE TITLE
[Pixel XL, OS 9, 2.16.0 and others] Crash when incoming notification comes and call is on air

### ISSUE THREAD

**Issue by vitalii-p** [opentok/opentok-android-sdk-samples#228]
I've started video conversation and during videocall I got notification. In case of 'do not disturb' mode everything runs smoothly, but if notification is with sound - I've got next error

`E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.com.com, PID: 15861
java.lang.IllegalThreadStateException
at java.lang.Thread.start(Thread.java:724)
at com.opentok.android.v3.DefaultAudioDriver$AudioInputThread.start(DefaultAudioDriver.java:552)
at com.opentok.android.v3.DefaultAudioDriver.statelessStartCapturer(DefaultAudioDriver.java:400)
at com.opentok.android.v3.DefaultAudioDriver.onAudioFocusChange(DefaultAudioDriver.java:357)
at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2278)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

Checked with several devices and OS Versions - but was able to reproduce on first Pixel only.

**Comment by robjperez** [comment]
Going to close this due to inactivity.

Please reopen if still crashes on 2.17
