### ISSUE TITLE
Crash on Play Store build 

### ISSUE THREAD

**Issue by shahalRahman** [opentok/opentok-android-sdk-samples#237]
OpenTok version 2.15.3 is working fine in Debug and Release builds. But when downloading from PlayStore, it's crashing.
From the logs i got these lines.
`2019-08-13 13:30:59.510 32347-32347/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sociavi.sappv2, PID: 32347
    java.lang.NoSuchMethodError: no static or non-static method "Lcom/opentok/android/v3/debug/NativeLogToken;.getLogLevelNative(J)I"
        at com.opentok.android.v3.debug.NativeLogToken.registerNatives(Native Method)
        at com.opentok.android.v3.debug.NativeLogToken.<clinit>(:2)
        at com.opentok.android.v3.debug.Log.<init>(:8)
        at com.opentok.android.v3.debug.JavaLogToken.<init>(:5)
        at com.opentok.android.v3.debug.OtLog.a(:1)
        at com.opentok.android.v3.Session.<clinit>(:1)
        at com.opentok.android.v3.Session$Builder.a(:13)
        at com.opentok.android.Session.<init>(:36)
        at com.opentok.android.Session$Builder.a(:1)
        at com.sociavi.sappv2.OTSessionManager.a(:19)
        at com.sociavi.sappv2.OTSessionManager$2$2.run(:3)
        at android.app.Activity.runOnUiThread(Activity.java:6347)
        at com.sociavi.sappv2.OTSessionManager$2.onResponse(:19)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(:3)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)`

**Comment by shahalRahman** [comment]
It's working fine now. The issue is when building Android App Bundle with 

`buildTypes {
    release {
        lintOptions {
            checkReleaseBuilds false
            abortOnError false
        }
        minifyEnabled true
        shrinkResources true
        proguardFiles getDefaultProguardFile(
                'proguard-android-optimize.txt'),
                'proguard-rules.pro'
    }
}`

And 
`android.enableR8=true`

in gradle.properties
So, I've made these changes

`buildTypes {
    release {
        lintOptions {
            checkReleaseBuilds false
            abortOnError false
        }
        minifyEnabled false
        shrinkResources false
    }
}`

and also removed android.enableR8 from gradle.properties.
