### ISSUE TITLE
Opentok not releasing camera for other plugins

### ISSUE THREAD

**Issue by HannaSanford** [opentok/opentok-android-sdk-samples#238]
We wrote a cordova plugin based on https://github.com/opentok/opentok-android-sdk-samples/tree/master/Basic-Video-Chat which works to join a video call from an android tablet. It shows the tablet's forward facing camera in a preview box while showing the other attendee on the screen and including a hang up button. The plugin performs as expected, however, when we try to use another plugin involving the camera after making a call (even if the other party doesn't answer), the other plugin is unable to activate the camera. I have gone through the documentation and samples and been unable to find anything missing that might get the plugin to release the camera. 

Error: "Sorry, the Android camera encountered a problem. You may need to restart the device" appears on screen at launch of other plugin.

Our current endCall function looks like this:
```   
public void endCall() {
        mSession.unsubscribe(mSubscriber);
        mSession.unpublish(mPublisher);
        mSession.disconnect();
        VideoCall.this.finish();
    }
```

- have tried additionally calling destroy() on the publisher
- have tried calling removeView() on the publisher and subscriber view containers
- have tried calling setPublishVideo(false) and then destroying the BaseVideoCapturer

Other info:
- Android 7.0
- Ionic Cordova app
- com.opentok.android:opentok-android-sdk:2.16.+

Stack trace of error
```
2019-08-12 14:41:43.570 28685-28685/com.snap40.raptor W/CaptureActivity: Unexpected error initializing camera
	java.lang.RuntimeException: Fail to connect to camera service
		at android.hardware.Camera.<init>(Camera.java:571)
		at android.hardware.Camera.open(Camera.java:415)
		at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:78)...
```

**Comment by HannaSanford** [comment]
Turns out after much experimentation it needs to be
``` 
public void endCall() {
        if(mSession != null){
            if (mSubscriber != null) {
                mSubscriberViewContainer.removeView(mSubscriber.getView());
                mSession.unsubscribe(mSubscriber);
                mSubscriber.destroy();
                mSubscriber = null;
            }

            if (mPublisher != null) {
                mPublisherViewContainer.removeView(mPublisher.getView());
                mSession.unpublish(mPublisher);
                mPublisher.destroy();
                mPublisher = null;
            }
            mSession.disconnect();
        }

        VideoCall.this.finish();
    }
```
