### ISSUE TITLE
App crashing in release mode debug mode working fine

### ISSUE THREAD

**Issue by maheshordex** [opentok/opentok-android-sdk-samples#298]
The app is working on debug mode but when I generate APK with release mode app crashing with below warnings.

```
W/System.err: java.lang.NoSuchMethodError: no static method "Lorg/otwebrtc/WebRtcClassLoader;.getClassLoader()Ljava/lang/Object;"
2020-08-15 19:36:17.284 6016-6016/com.app.xxxxxxx W/System.err:     at com.opentok.android.Utils.init_otc_engine(Native Method)
2020-08-15 19:36:17.284 6016-6016/com.app.xxxxxxx W/System.err:     at com.opentok.android.Utils.b(Unknown Source:5)
2020-08-15 19:36:17.284 6016-6016/com.app.xxxxxxx W/System.err:     at com.opentok.android.Session.<init>(Unknown Source:70)
2020-08-15 19:36:17.286 6016-6016/com.app.xxxxxxx W/System.err:     at com.opentok.android.Session$Builder.build(Unknown Source:25)

2020-08-15 20:01:44.710 7319-7319/com.app.xxxx E/rtc: #
    # Fatal error in: ../../src/sdk/android/src/jni/jni_generator_helper.cc, line 59
    # last system error: 2
    # Check failed: !env->ExceptionCheck()
    # error during GetMethodID: getClassLoader, ()Ljava/lang/Object;

```

Proguard-rules.pro
```
# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile
-dontwarn okio.**
-dontwarn javax.annotation.**

-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }

# Only required if you use AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}

-ignorewarnings
-keep class * {
    public private *;
}

-keep class com.stripe.** { *; }
-keep class com.stripe.android.** { *; }

# for pubnub check below

# for glide app only

-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

# If you're targeting any API level less than Android API 27, also include: ```pro
-dontwarn com.bumptech.glide.load.resource.bitmap.VideoDecoder

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile

-keepattributes Exceptions, InnerClasses, Signature, Deprecated, SourceFile, LineNumberTable, *Annotation*, EnclosingMethod

-keep class com.google.android.gms.ads.identifier.** { *; }

# Joda-Time
-dontwarn org.joda.time.**
-keep class org.joda.time.** { *; }

# Gson
-dontwarn sun.misc.**
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.examples.android.model.** { *; }
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# OkHttp3
-dontwarn okhttp3.**
-dontwarn org.codehaus.mojo.animal_sniffer.*
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

# Okio
-dontwarn okio.**

# Retrofit 2.X
-dontwarn retrofit2.**
-dontwarn javax.annotation.**
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}
-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}

# Logback and slf4j-api
-dontwarn ch.qos.logback.core.net.*
-dontwarn org.slf4j.**
-keep class ch.qos.** { *; }
-keep class org.slf4j.** { *; }

# PubNub
-dontwarn com.pubnub.**
-keep class com.pubnub.** { *; }

-dontwarn android.widget.**
-keep class android.widget.** { *; }
-keep class java.lang.reflect.Field { *; }
-keep class org.webrtc.** { *; }
-keep class com.opentok.** { *; }
```

**Comment by maheshordex** [comment]
@deniskras @robjperez @willyaranda @jaoo  can anyone help here ?

**Comment by rperezcubero** [comment]
You need to `keep` otwebrtc classes.

Please modify your proguard file to include:
```
-keep class org.otwebrtc.** { *; }
```
