### ISSUE TITLE
App crash intermittently while initializing an opentok session

### ISSUE THREAD

**Issue by ameybhandarkar** [opentok/opentok-android-sdk-samples#393]
I am getting a crash intermittently while initializing an opentok session. Following are the logs:
 
`Fatal Exception: java.lang.NoClassDefFoundError: com.opentok.android.Session
       at com.opentok.android.Session$Builder.build(SourceFile)
       at iDocsWebpkg.iDocsWebpkg.ui.activities.NotificationDetailActivity.initializeSession(NotificationDetailActivity.java:1193)
       at iDocsWebpkg.iDocsWebpkg.ui.activities.NotificationDetailActivity.onMeetingStarted(NotificationDetailActivity.java:1671)
       at iDocsWebpkg.iDocsWebpkg.ui.fragments.VitalsFragment$18.onResponse(VitalsFragment.java:1155)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

`Caused by java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/iDocsWebpkg.iDocsWebpkg-1/base.apk"],nativeLibraryDirectories=[/data/app/iDocsWebpkg.iDocsWebpkg-1/lib/arm, /data/app/iDocsWebpkg.iDocsWebpkg-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libopentok.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:972)
       at java.lang.System.loadLibrary(System.java:1567)
       at com.opentok.android.Loader.load(SourceFile)
       at com.opentok.android.Session.<clinit>(SourceFile)
       at com.opentok.android.Session$Builder.build(SourceFile)
       at iDocsWebpkg.iDocsWebpkg.ui.activities.NotificationDetailActivity.initializeSession(NotificationDetailActivity.java:1193)
       at iDocsWebpkg.iDocsWebpkg.ui.activities.NotificationDetailActivity.requestPermissions(NotificationDetailActivity.java:1163)
       at java.lang.reflect.Method.invoke(Method.java)
       at pub.devrel.easypermissions.EasyPermissions.runAnnotatedMethods(EasyPermissions.java:378)
       at pub.devrel.easypermissions.EasyPermissions.onRequestPermissionsResult(EasyPermissions.java:236)
       at iDocsWebpkg.iDocsWebpkg.ui.activities.NotificationDetailActivity.onRequestPermissionsResult(NotificationDetailActivity.java:902)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7473)
       at android.app.Activity.dispatchActivityResult(Activity.java:7299)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4516)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
       at android.app.ActivityThread.-wrap22(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

I am getting this crash only on Samsung Galaxy On8 device which is running on Android 7.0. 
I have already tried a solution mentioned here 
https://github.com/opentok/opentok-android-sdk-samples/issues/314

Please let me know if anybody can help.

**Comment by v-kpheng** [comment]
@ameybhandarkar, apologies for the belated reply.

This may be related to ProGuard rules, since you linked a similar issue.  Please find updated rules here: https://tokbox.com/developer/sdks/android/#proguard-rules-needed-by-the-vonage-android-sdk.

Closing, since this is an aged issue.  If you're still seeing issues, please file another issue.  Thanks!
