### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Session has been closed; further changes are illegal.

### ISSUE THREAD

**Issue by nitinmisra27** [opentok/opentok-android-sdk-samples#466]
**Describe the bug**
Fatal Exception: java.lang.IllegalStateException: Session has been closed; further changes are illegal.

**To Reproduce**
Unable to reproduce it

```
# Crashlytics - Stack trace
# Application: 
# Platform: android
# Version: 
# Issue: 11ce39585df796cab9de9be13640f7eb
# Session: 647092F702420001079C01DD1AB9257A_DNE_0_v2
# Date: Fri May 26 2023 04:11:59 GMT-0700 (Pacific Daylight Time)

Fatal Exception: java.lang.IllegalStateException: Session has been closed; further changes are illegal.
       at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:893)
       at android.hardware.camera2.impl.CameraCaptureSessionImpl.stopRepeating(CameraCaptureSessionImpl.java:424)
       at com.opentok.android.Camera2VideoCapturer.stopCapture(SourceFile:31)
       at com.opentok.android.PublisherKit.d(SourceFile:2)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8399)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by v-kpheng** [comment]
@nitinmisra27, thanks for filing this report.
That said, there's not much to go by.  What are the steps to reproduce?  Does this impact all Android devices?  What versions of the SDK can reproduce the issue.  Does the problem go away if you use the native version?

**Comment by nitinmisra27** [comment]
@v-kpheng I'm also unable to reproduce it with normal use seems like an edge case when the user finishes up with a video call. This was discovered in `com.opentok.android:opentok-android-sdk:2.25.0`. For the time being I've updated the SDK v2.25.2 and closed the issues. Let me know if you need more information.
