### ISSUE TITLE
TokBox crashes when we pause the publisher and open device camera to capture image

### ISSUE THREAD

**Issue by dev-android1** [opentok/opentok-android-sdk-samples#482]
Please see logs below for crash issue

Fatal Exception: com.opentok.android.Camera2VideoCapturer$Camera2Exception: CAMERA_IN_USE (4): connectHelper:2134: Higher-priority client using camera, ID "1" currently unavailable
       at com.opentok.android.Camera2VideoCapturer.initCamera(:70)
       at com.opentok.android.Camera2VideoCapturer.doInit(:19)
       at com.opentok.android.Camera2VideoCapturer.init(:16)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by v-kpheng** [comment]
@dev-android1, I'm going to close this, since it's missing a lot of important details.  Can you please refile and answer the questions in the Issue template: https://github.com/opentok/opentok-android-sdk-samples/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Thanks!
