### ISSUE TITLE
lib/arm64/libopentok.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by rahul-shah** [opentok/opentok-android-sdk-samples#74]
Hi guys i get this error when i use my application with a 64 bit device. Samsung s6 and a nexus 9. Could you please help me with this. I am using the SDK version 2.5.0

**Comment by madhavc** [comment]
@rahul-shah will you please provide the logs of the error and what sample app are you using?

**Comment by vrunoa** [comment]
hey @madhavc I got the same error on a Samsung S6, here's my crash log:
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ar.com.portalsalud.doc24.android-1/base.apk"],nativeLibraryDirectories=[/data/app/ar.com.portalsalud.doc24.android-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libopentok.so"
       at java.lang.Runtime.loadLibrary(Runtime.java:367)
       at java.lang.System.loadLibrary(System.java:988)
       at com.opentok.android.Session.<clinit>(Session.java:52)
       at ar.com.portalsalud.doc24.android.activities.VideoCallActivity.connect(VideoCallActivity.java:72)
       at ar.com.portalsalud.doc24.android.activities.VideoCallActivity.onRequestPermissionsResult(VideoCallActivity.java:169)
       at android.support.v4.app.ActivityCompat$1.run(ActivityCompat.java:333)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6843)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```
I believe you still don't support **ARMv8** devices, is that correct ?

**Comment by wobbals** [comment]
Correct; 64-bit support is not available yet. Please just target 32-bit architecture for now.

**Comment by vrunoa** [comment]
thanks @wobbals . Any idea when would 64-bit be release ?  Any possibility to have it before June ?

**Comment by alexsorokoletov** [comment]
+1 to arm64 suport for Android

**Comment by robjperez** [comment]
Upcoming version of the SDK (2.9.0) will have arm64 support
