### ISSUE TITLE
SDK crashes with Subscriber type token

### ISSUE THREAD

**Issue by baneizalfe** [opentok/opentok-android-sdk-samples#93]
For purpose of test I made 3 flavors of app with appropriate tokens
Publisher 1
Publisher 2
Subscriber

Connecting Publiser2Publisher works, but when i launch app with subscriber type if token it crashes all the time

`java.lang.IllegalArgumentException: unknown type code 1500
at com.opentok.android.OpentokError$ErrorCode.fromTypeCode(OpentokError.java:143)
at com.opentok.android.OpentokError.<init>(OpentokError.java:174)
at com.opentok.android.PublisherKit.error(PublisherKit.java:684)
at dalvik.system.NativeStart.run(Native Method)
Fatal signal 6 (SIGABRT) at 0x000076a4 (code=-6), thread 32412`

I created all tokens to last for 30 days so it is not expired one. Even so it should not crash right?

**Comment by robjperez** [comment]
thanks for reporting this. It'll be fixed in the new version of the SDK (2.9.0)
